# PRODUCTOS

GET http://localhost:3000/api/productos

###

POST http://localhost:3000/api/productos
Content-Type: application/json

{
  "nombre": "Producto de prueba",
  "precio": 100,
  "descripcion": "Descripción del producto de prueba",
  "categoria": "Categoria de prueba"
}


###

GET http://localhost:3000/api/productos/1

###

PUT http://localhost:3000/api/productos/1
Content-Type: application/json

{
  "nombre": "Producto actualizado",
  "precio": 150,
  "descripcion": "Descripción actualizada del producto",
  "categoria": "Categoria actualizada"
}

###
DELETE http://localhost:3000/api/productos/1

# CATEGORÍAS
GET http://localhost:3000/api/categorias
